<a href="https://colab.research.google.com/github/marneusz/data-science-bootcamp/blob/master/02_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [3]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__doc__', '__file__', '__git_revision__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_distributor_init', '_globals', '_mat', '_pytesttester', 'abs', 'absolute', 'absolute_import

In [0]:
help(np.array)

In [6]:
x = np.array([1,3])
x

array([1, 3])

In [7]:
print(x)

[1 3]


In [8]:
type(x)

numpy.ndarray

In [9]:
x.ndim

1

In [10]:
x.shape

(2,)

In [11]:
x.size

2

In [12]:
x.dtype

dtype('int64')

In [0]:
y = np.array([1.2, 3.4, 2.1])

In [15]:
print(y)

[1.2 3.4 2.1]


In [16]:
y.dtype

dtype('float64')

In [0]:
x = np.array([[2,3],[-3,1]])

In [19]:
print(x)

[[ 2  3]
 [-3  1]]


In [20]:
x.ndim

2

In [21]:
x.shape

(2, 2)

In [0]:
y = np.array([[2,3,1],[-2,-3,-1]])

In [25]:
y.shape

(2, 3)

###3D###


In [0]:
x = np.array(
    [[[4, 3, 1],
      [4, 2, 2]],
     
     [[2, 5, 1],
      [1, 7, 4]],
     
     [[2, 5, 1],
      [1, 7, 4]]]
    )

In [32]:
print(x)

[[[4 3 1]
  [4 2 2]]

 [[2 5 1]
  [1 7 4]]

 [[2 5 1]
  [1 7 4]]]


In [33]:
x.ndim

3

In [34]:
x.shape

(3, 2, 3)

### TYPY DANYCH ###

In [0]:
A = np.array([2, 3.5, 6.1])

In [40]:
A.dtype

dtype('float64')

In [0]:
A = np.array([2, 3.5, 6.1], dtype = 'complex')

In [42]:
A.dtype

dtype('complex128')

In [43]:
A

array([2. +0.j, 3.5+0.j, 6.1+0.j])

In [0]:
A = np.array([2, 3.5, 6.1], dtype = 'int')

In [45]:
A

array([2, 3, 6])

In [46]:
A.dtype

dtype('int64')

In [0]:
B = np.array([True, False])

In [48]:
B.dtype

dtype('bool')

In [0]:
# Przykład numpy'owego typu, e.g. dla obrazów
B = np.array([201,301,10], dtype = np.uint8)

In [52]:
B.dtype

dtype('uint8')

In [53]:
np.zeros(shape=(4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [54]:
np.zeros(shape=(4,10), dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [56]:
np.ones(shape = (5,5),dtype = 'int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [57]:
np.full(shape = (3,3), fill_value=4, dtype = 'int')

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [59]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [62]:
np.arange(start = 5, stop = 10)

array([5, 6, 7, 8, 9])

In [63]:
np.arange(start = 10, stop = 100, step = 10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [64]:
np.arange(start = 5, stop = -5, step = -0.5)

array([ 5. ,  4.5,  4. ,  3.5,  3. ,  2.5,  2. ,  1.5,  1. ,  0.5,  0. ,
       -0.5, -1. , -1.5, -2. , -2.5, -3. , -3.5, -4. , -4.5])

In [65]:
np.linspace(start=1, stop=10, num=50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [67]:
np.linspace(start=0, stop=1, num=10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [0]:
A = np.arange(15)

In [74]:
A.reshape((3,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [76]:
A.reshape((3,-1))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [77]:
A.reshape((-1,3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

### OPERACJE NA TABLICACH ###

In [0]:
A = np.array([3,1,2,5])

In [0]:
B = np.array([12, 3, 4, 5])

In [81]:
A

array([3, 1, 2, 5])

In [82]:
print(B)

[12  3  4  5]


In [83]:
A+B

array([15,  4,  6, 10])

In [84]:
A-B

array([-9, -2, -2,  0])

In [85]:
A*B

array([36,  3,  8, 25])

In [86]:
A/B

array([0.25      , 0.33333333, 0.5       , 1.        ])

In [92]:
np.add(A,B)

array([15,  4,  6, 10])

In [93]:
np.divide(A,B)

array([0.25      , 0.33333333, 0.5       , 1.        ])

In [88]:
A**B

array([531441,      1,     16,   3125])

In [89]:
A+3

array([6, 4, 5, 8])

In [90]:
2 * A

array([ 6,  2,  4, 10])

In [91]:
A+3*B

array([39, 10, 14, 20])

In [0]:
x = np.array([[1,2],[3,4]])

In [0]:
y = np.array([[6,0],[-1,2]])

In [97]:
print(x,'\n')
print(y)

[[1 2]
 [3 4]] 

[[ 6  0]
 [-1  2]]


In [98]:
np.dot(x,y)

array([[ 4,  4],
       [14,  8]])

In [99]:
y.dot(x)

array([[ 6, 12],
       [ 5,  6]])

In [100]:
x @ y

array([[ 4,  4],
       [14,  8]])

### GENEROWANIE LICZB PSEUDOLOSOWYCH ###

In [0]:
np.random.seed(0)

In [102]:
np.random.randn()

1.764052345967664

In [103]:
np.random.randn(10)

array([ 0.40015721,  0.97873798,  2.2408932 ,  1.86755799, -0.97727788,
        0.95008842, -0.15135721, -0.10321885,  0.4105985 ,  0.14404357])

In [104]:
np.random.randn(10,4)

array([[ 1.45427351,  0.76103773,  0.12167502,  0.44386323],
       [ 0.33367433,  1.49407907, -0.20515826,  0.3130677 ],
       [-0.85409574, -2.55298982,  0.6536186 ,  0.8644362 ],
       [-0.74216502,  2.26975462, -1.45436567,  0.04575852],
       [-0.18718385,  1.53277921,  1.46935877,  0.15494743],
       [ 0.37816252, -0.88778575, -1.98079647, -0.34791215],
       [ 0.15634897,  1.23029068,  1.20237985, -0.38732682],
       [-0.30230275, -1.04855297, -1.42001794, -1.70627019],
       [ 1.9507754 , -0.50965218, -0.4380743 , -1.25279536],
       [ 0.77749036, -1.61389785, -0.21274028, -0.89546656]])

In [107]:
np.random.rand()

0.3687251706609641

In [108]:
np.random.rand(10,2)

array([[0.82099323, 0.09710128],
       [0.83794491, 0.09609841],
       [0.97645947, 0.4686512 ],
       [0.97676109, 0.60484552],
       [0.73926358, 0.03918779],
       [0.28280696, 0.12019656],
       [0.2961402 , 0.11872772],
       [0.31798318, 0.41426299],
       [0.0641475 , 0.69247212],
       [0.56660145, 0.26538949]])

In [109]:
np.random.randint(10) # miedzy 0 a 9

9

In [110]:
np.random.randint(low=-15, high=-2, size=20)

array([ -5, -14, -11,  -5,  -9,  -4,  -7,  -4, -13, -12, -15, -15,  -9,
       -15,  -9, -12,  -5, -12,  -7,  -3])

In [113]:
np.random.choice([4,2,3,1,4,7,467,4321])

467

In [114]:
np.random.choice(['python', 'java','sql'])

'python'

In [116]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [118]:
np.random.shuffle(data)
data #zmienia obiekt

array([8, 6, 2, 1, 9, 4, 0, 7, 5, 3])

### PODSTAWOWE FUNKCJE ###