<a href="https://colab.research.google.com/github/marneusz/data-science-bootcamp/blob/master/02_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [3]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__doc__', '__file__', '__git_revision__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_distributor_init', '_globals', '_mat', '_pytesttester', 'abs', 'absolute', 'absolute_import

In [0]:
help(np.array)

In [6]:
x = np.array([1,3])
x

array([1, 3])

In [7]:
print(x)

[1 3]


In [8]:
type(x)

numpy.ndarray

In [9]:
x.ndim

1

In [10]:
x.shape

(2,)

In [11]:
x.size

2

In [12]:
x.dtype

dtype('int64')

In [0]:
y = np.array([1.2, 3.4, 2.1])

In [15]:
print(y)

[1.2 3.4 2.1]


In [16]:
y.dtype

dtype('float64')

In [0]:
x = np.array([[2,3],[-3,1]])

In [19]:
print(x)

[[ 2  3]
 [-3  1]]


In [20]:
x.ndim

2

In [21]:
x.shape

(2, 2)

In [0]:
y = np.array([[2,3,1],[-2,-3,-1]])

In [25]:
y.shape

(2, 3)

###3D###


In [0]:
x = np.array(
    [[[4, 3, 1],
      [4, 2, 2]],
     
     [[2, 5, 1],
      [1, 7, 4]],
     
     [[2, 5, 1],
      [1, 7, 4]]]
    )

In [32]:
print(x)

[[[4 3 1]
  [4 2 2]]

 [[2 5 1]
  [1 7 4]]

 [[2 5 1]
  [1 7 4]]]


In [33]:
x.ndim

3

In [34]:
x.shape

(3, 2, 3)

### TYPY DANYCH ###

In [0]:
A = np.array([2, 3.5, 6.1])

In [40]:
A.dtype

dtype('float64')

In [0]:
A = np.array([2, 3.5, 6.1], dtype = 'complex')

In [42]:
A.dtype

dtype('complex128')

In [43]:
A

array([2. +0.j, 3.5+0.j, 6.1+0.j])

In [0]:
A = np.array([2, 3.5, 6.1], dtype = 'int')

In [45]:
A

array([2, 3, 6])

In [46]:
A.dtype

dtype('int64')

In [0]:
B = np.array([True, False])

In [48]:
B.dtype

dtype('bool')

In [0]:
# Przykład numpy'owego typu, e.g. dla obrazów
B = np.array([201,301,10], dtype = np.int8)

In [50]:
B.dtype

dtype('int8')